export const blogs = [
  {
    id: 1,
    title: "The Future of Construction: Innovations and Trends",
    date: "2023-10-01",
    desc: "Explore the latest innovations and trends shaping the future of construction, from sustainable materials to advanced technologies.",
    img: "/assets/img/blogs/blog1.jpg",
    link: "/blog/future-of-construction",
    category: "Announcement",
    trending: true,
  },
  {
    id: 2,
    title: "Sustainable Building Materials: A Comprehensive Guide",
    date: "2023-09-15",
    desc: "Discover the benefits and applications of sustainable building materials in modern construction projects.",
    img: "/assets/img/blogs/blog2.jpg",
    link: "/blog/sustainable-building-materials",
    category: "Insight",
    trending: false,
  },
  {
    id: 3,
    title: "Top 10 Construction Technologies to Watch in 2024",
    date: "2023-08-20",
    desc: "Stay ahead of the curve with our roundup of the top construction technologies set to revolutionize the industry in 2024.",
    img: "/assets/img/blogs/blog3.jpg",
    link: "/blog/construction-technologies",
    category: "Report",
    trending: true,
  },
  {
    id: 4,
    title: "The Importance of Safety in Construction Sites",
    date: "2023-07-10",
    desc: "Learn about the critical safety measures that should be implemented on construction sites to protect workers and ensure project success.",
    img: "/assets/img/blogs/blog4.jpg",
    link: "/blog/safety-in-construction",
    category: "Technology",
    trending: false,
  },
  {
    id: 5,
    title: "Innovative Design Trends in Modern Architecture",
    date: "2023-06-25",
    desc: "Explore the innovative design trends that are shaping modern architecture and influencing the way we build.",
    img: "/assets/img/blogs/blog5.jpg",
    link: "/blog/modern-architecture",
    category: "Architecture",
    trending: true,
  }
]