export const newsEvents = [
  {
    id: 1,
    type: "news",
    breaking:true,
    imageSrc: "/assets/img/news/news1.jpg",
    date: "2025-01-03",
    title: "Wells announces acquisition of GATE precast",
    desc: "Wells has announced the acquisition of GATE Precast, a subsidiary of GATE Petroleum Company",
    categories: ["Company News"],
    readMoreLink: "news-details",
  },
  {
    id: 2,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news2.jpg",
    date: "2024-11-26",
    title: "How prefabrication is gaining traction over masonry in K12 construction",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Events"],
    readMoreLink: "news-details",
  },
  {
    id: 3,
    type: "news",
    breaking:true,
    imageSrc: "/assets/img/news/news3.jpg",
    date: "2024-10-15",
    title: "The critical difference that maintenance makes in the lifespan of concrete structures",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Expertise"],
    readMoreLink: "news-details",
  },
  {
    id: 4,
    type: "news",
    breaking:true,
    imageSrc: "/assets/img/news/news1.jpg",
    date: "2024-09-15",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Events"],
    readMoreLink: "news-details",
  },
  {
    id: 5,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news2.jpg",
    date: "2024-08-01",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Company News"],
    readMoreLink: "news-details",
  },
  {
    id: 6,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news3.jpg",
    date: "2024-07-15",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Expertise"],
    readMoreLink: "news-details",
  },
  {
    id: 7,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news1.jpg",
    date: "2024-06-01",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Events"],
    readMoreLink: "news-details",
  },
  {
    id: 8,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news2.jpg",
    date: "2024-05-15",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Company News"],
    readMoreLink: "news-details",
  },
  {
    id: 9,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news3.jpg",
    date: "2024-04-20",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Expertise"],
    readMoreLink: "news-details",
  },
  {
    id: 10,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news2.jpg",
    date: "2024-08-01",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Events"],
    readMoreLink: "news-details",
  },
  {
    id: 11,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news3.jpg",
    date: "2024-04-20",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Expertise"],
    readMoreLink: "#",
  },
  {
    id: 12,
    type: "news",
    breaking:false,
    imageSrc: "/assets/img/news/news2.jpg",
    date: "2024-05-15",
    title: "lorem ipsum dolor sit amet, consectetur adipiscing elit",
    desc: "lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    categories: ["Company News"],
    readMoreLink: "news-details",
  },
];
