import mongoose from "mongoose";

const careerSchema = new mongoose.Schema({
    banner:{
        type:String,
        required:true
    },
    bannerAlt:{
        type:String,
        required:true
    },
    pageTitle:{
        type:String,
    },
    firstSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        image:{
            type:String,
        },
        imageAlt:{
            type:String,
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            }
        }]
    },
    secondSection:{
        title:{
            type:String,
            required:true
        },
        description:{
            type:String,
            required:true
        },
        items:[{
            title:{
                type:String,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            logo:{
                type:String,
                required:true
            },
            logoAlt:{
                type:String,
            }
        }]
    },
    thirdSection:{
        items:[{
            title:{
                type:String,
                required:true
            },
            mode:{
                type:String,
                required:true
            },
            jobType:{
                type:String,
                required:true
            },
        }]
    },
    metaTitle:{
        type:String,
    },
    metaDescription:{
        type:String,
    }
})

export default mongoose.models.Career || mongoose.model("Career", careerSchema);